/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.busboard;

import io.bus.Bus;
import io.bus.TooManyPassengers;
import io.covidcontroller.CovidController;
import javax.swing.JOptionPane;

/**
 *
 * @author azzeg
 */
public class BusBoard extends javax.swing.JFrame {

    /**
     * Creates new form BusBoard
     */
    public BusBoard() {
        initComponents();
        labelNumPassenger.setText(Integer.toString(bus2.getNumPassenger()));
        bus2.addVetoableChangeListener(covidController2);
        bus2.addPropertyChangeListener((event) -> {
            if ( "numPassenger".equals( event.getPropertyName() ) ){
                labelNumPassenger.setText( String.valueOf(event.getNewValue()) );
            }
        });
        
        labelDoorOpen.setText(Boolean.toString(bus2.isDoorOpen()));
        bus2.addPropertyChangeListener((event) -> {
            if ( "doorOpen".equals( event.getPropertyName() ) ){
                labelDoorOpen.setText( String.valueOf(event.getNewValue()) );
                btnEnter.setEnabled(true);
            }
        });
        bus2.activate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bus2 = new io.bus.Bus();
        covidController2 = new io.covidcontroller.CovidController();
        labelNumPassenger = new javax.swing.JLabel();
        labelDoorOpen = new javax.swing.JLabel();
        labelTextNumPassenger = new javax.swing.JLabel();
        labelTextDoorOpen = new javax.swing.JLabel();
        tfEnter = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNumPassenger.setText("0");
        labelNumPassenger.setToolTipText("");

        labelDoorOpen.setText("false");

        labelTextNumPassenger.setText("Passenger number:");

        labelTextDoorOpen.setText("Door open:");

        tfEnter.setText("1");

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTextNumPassenger)
                        .addGap(18, 18, 18)
                        .addComponent(labelNumPassenger)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTextDoorOpen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnter, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDoorOpen)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumPassenger)
                    .addComponent(labelDoorOpen)
                    .addComponent(labelTextNumPassenger)
                    .addComponent(labelTextDoorOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter))
                .addGap(92, 92, 92))
        );

        labelNumPassenger.getAccessibleContext().setAccessibleName("");
        labelDoorOpen.getAccessibleContext().setAccessibleName("labelDoorOpen");
        labelTextNumPassenger.getAccessibleContext().setAccessibleName("labelTextNumPassenger");
        labelTextDoorOpen.getAccessibleContext().setAccessibleName("labelTextDoorOpen");
        tfEnter.getAccessibleContext().setAccessibleName("tfEnter");
        btnEnter.getAccessibleContext().setAccessibleName("btnEnter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        try{
            int increase=Integer.parseInt(tfEnter.getText());
            if(increase <1 || increase>5){
                JOptionPane.showMessageDialog(null, "Insert a number in 1-5", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                bus2.increasePassengers(increase);
                btnEnter.setEnabled(false);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Incorrect number", "Error", JOptionPane.ERROR_MESSAGE);
        }catch(TooManyPassengers e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private io.bus.Bus bus2;
    private io.covidcontroller.CovidController covidController2;
    private javax.swing.JLabel labelDoorOpen;
    private javax.swing.JLabel labelNumPassenger;
    private javax.swing.JLabel labelTextDoorOpen;
    private javax.swing.JLabel labelTextNumPassenger;
    private javax.swing.JTextField tfEnter;
    // End of variables declaration//GEN-END:variables
}
